repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-docstring-first
        stages:
        - commit
        - push
    -   id: check-merge-conflict
        stages:
        - push
    -   id: requirements-txt-fixer
        stages:
          - commit
          - push
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        files: 'pullkin/.*'
        args: [--profile=black]
        stages:
        - commit
        - push
      - id: isort
        files: 'tests/.*'
        args: [--profile=black]
        stages:
        - commit
        - push
-   repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        args: [--preview]
