language: python

python:
  - "3.4"
  - "3.6"
  - "3.8"
  - "3.9"
  - "nightly"
  - "pypy3"

install: pip install .[listen,example]

script:
  - python -m "pullkin" --sender-id=722915550290 --no-listen
