site_name: "Pullkin"
repo_url: https://github.com/whiteapfel/Pullkin

theme:
  name: "material"
  language: ru
#  custom_dir: 'docs/theme'
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/lightbulb-outline
        name: "Dark Theme"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/lightbulb
        name: "Light Theme"
  features:
    - content.tabs.link
    - content.code.annotate
    - announce.dismiss
    - navigation.tabs
nav:
- Main: index.md
- Guide:
  - Install: guide/install.md
  - Main methods: guide/methods.md
  - Example: guide/examples.md
- API:
  - Modules (Модули): API/modules.md
  - Types (Модели): API/types.md


plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: google
          show_if_no_docstring: false
          members_order: source
          show_symbol_type_heading: true
          docstring_options:
            ignore_init_summary: true

markdown_extensions:
- pymdownx.details
- pymdownx.superfences
- pymdownx.highlight
- pymdownx.extra