name: Publish package to PyPI

on:
  release:
    types: [ published ]

jobs:
  build-n-publish:
    name: Build and publish package to PyPI
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install pypa/build
        run: >-
          python3 -m pip install --user --upgrade setuptools wheel

      - name: Build a binary wheel and a source tarball
        env:
          TAG_VERSION: ${{ github.event.release.tag_name }}
        run: >-
          python3 setup.py sdist bdist_wheel

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}